drop table if exists ss_task;
drop table if exists ss_user;

drop table if exists tb_base_city;
drop table if exists tb_base_enum;
drop table if exists tb_evaluate;
drop table if exists tb_court;
drop table if exists tb_event;
drop table if exists tb_event_evaluate;
drop table if exists tb_event_owner;
drop table if exists tb_event_partake; 
drop table if exists tb_event_court; 
drop table if exists tb_event_startuser; 
drop table if exists tb_file_store;
drop table if exists tb_tennis_user;
drop table if exists tb_base_user;
drop table if exists tb_group;
drop table if exists tb_user_group;
drop table if exists tb_court_images;
drop table if exists tb_court_evaluate;
drop table if exists tb_user_friends;
drop table if exists tb_user_image;

create table ss_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

create table ss_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);



-- frankswu 


create table tb_group (
    id bigint generated by default as identity,
    group_Name varchar(255) null,
    group_desc varchar(255) null,
    primary key (id)
) ;

create table tb_user_group (
    user_id bigint  not null,
    group_id bigint not null,
    primary key (user_id,group_id)
) ;

--	基础城市或地址 


create table tb_base_city (
    id bigint generated by default as identity,
    city_Name varchar(255) null,
    city_Type varchar(255) null,
    primary key (id)
) ;

-- 基础枚举数据表


create table tb_base_enum (
    id bigint generated by default as identity,
    enum_Type varchar(255) null,
    enum_Value varchar(255) null,
    enum_Desc varchar(255) null,
    primary key (id)
) ;

--基础用户



create table tb_base_user (
    id bigint generated by default as identity,
    name varchar(255) null,
    password varchar(255) null,
    account varchar(255) null,
    register_Date TIMESTAMP  null,
    roles varchar(255) null,
    group_List bigint  null,
    primary key (id)
) ;

--球场


create table tb_court (
    id bigint generated by default as identity,
    title varchar(255) null,
    fee varchar(255) null,
    city_id bigint  not null,
    court_Count varchar(255) null,
    end_Time TIMESTAMP null,
    start_Time TIMESTAMP null,
    phone varchar(255) null,
    district_id bigint not null,
    address varchar(255) null,
    weights varchar(255) null,
    latitude double  null,
    longitude double  null,
    court_Desc varchar(255) null,
    primary key (id)
) ;

create table tb_court_images (
    court_id bigint  not null,
    image_id bigint not null,
    primary key (court_id,image_id)
) ;

create table tb_court_evaluate (
    id bigint generated by default as identity,
    court_id bigint  not null,
    evaluate_id bigint not null,
    primary key (id)
) ;

-- 评价model

create table tb_evaluate (
	id bigint generated by default as identity,
    score bigint  null,
    evaluate varchar(255) null,
    category_id bigint not null,
    primary key (id)
) ;

create table tb_event_evaluate (
    event_id bigint  not null,
    evaluate_id bigint not null,
    primary key (event_id,evaluate_id)
) ;

--


create table tb_event (
	id bigint generated by default as identity,
    event_Time TIMESTAMP  null,
    commit_Time TIMESTAMP  null,
    require varchar(255) null,
    category_id bigint  null,
    statues bigint null,
    address varchar(255) null,
    totol_Price double  null,
    phone varchar(255) null,
    latitude double  null,
    longitude double  null,
    descrition varchar(255) null,
    remark varchar(255) null,
    title varchar(255)  null,
    event_status_id bigint  null,
    weight bigint  null,
    primary key (id)
) ;



create table tb_event_owner (
    event_id bigint  not null,
    owner_id bigint not null,
    primary key (event_id,owner_id)
) ;


create table tb_event_partake (
    event_id bigint  not null,
    partake_id bigint not null,
    primary key (event_id,partake_id)
) ;

create table tb_event_court (
    event_id bigint  not null,
    court_id bigint not null,
    primary key (event_id,court_id)
) ;

create table tb_event_startuser (
    event_id bigint  not null,
    startuser_id bigint not null,
    primary key (event_id,startuser_id)
) ;

-- 文件存储


create table tb_file_store (
	id bigint generated by default as identity,
    file_Url varchar(255) null,
    file_Name varchar(255) null,
    file_Type bigint  null,
    primary key (id)
) ;

-- 球友


create table tb_tennis_user (
	id bigint not null,
    user_id bigint  null,
    integral varchar(255) null,
    last_Login_Date varchar(255) null,
    personal_Info bigint  null,
    gender bigint  null,
    account_Level varchar(255) null,
    birthday varchar(255) null,
    state bigint  null,
    tennis_Age int(11)  null,
    phone varchar(255) null,
    address varchar(255) null,
    device_Flag varchar(255) null,
    tennis_Level int(11)  null,
    email varchar(255) null,
    age int(11)  null,
    login_Times int(11)  null,
    phote varchar(255) null,
    gender_id bigint null,
    state_id bigint null,
    primary key (id)
) ;

create table tb_user_friends (
    user_id bigint  not null,
    evaluate_id bigint not null,
    primary key (user_id,evaluate_id)
) ;

create table tb_user_image (
    user_id bigint  not null,
    image_id bigint not null,
    primary key (user_id,image_id)
) ;

