drop table if exists ss_task;
drop table if exists ss_user;

create table ss_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

create table ss_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);



-- frankswu 
create table user_tb (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	roles varchar(255) null,
	register_date timestamp not null,
	primary key (id)
);

create table group_tb (
	id bigint generated by default as identity,
	group_name varchar(64) not null,
	group_desc varchar(255) null,
	primary key (id)
);

create table user_group_tb (
	user_id bigint not null,
	group_id bigint not null,
	primary key (user_id,group_id)
);


create table role_tb (
	id bigint generated by default as identity,
	role_name varchar(255) not null,
	permissions varchar(255) not null,
	primary key (id)
);

create table function_tb (
	id bigint generated by default as identity,
	function_name varchar(255) not null,
	function_desc varchar(255),
	page_id bigint not null,
	android_token varchar(255) not null,
	ios_token varchar(255) not null,
	baffles varchar(255),
	permissions varchar(255) ,
	primary key (id)
);


create table user_function_tb (
	user_id bigint not null,
	function_id bigint not null,
	primary key (user_id,function_id)
);

create table baffle_tb (
	id bigint generated by default as identity,
	baffle_name varchar(255) not null,
	baffle_desc varchar(255),
	baffle_type int not null,
	service_code varchar(255) not null,
	baffle_jsondata blob not null,
	model_class_name varchar(255) not null,
	model_id bigint not null,
	primary key (id)
);



